#!/usr/bin/env python3
"""Generate same-source DPDP Mandel initial pressure and displacement tables.

The generated data enforces the initial undrained storage closure

    Sbar * p0 + abar * f0 = 0

with the same coefficients used by dpdp_mandel_analytical.py.  The top
displacement history uses the analytical-script displacement shape and the
same absolute scale as the generated p0.
"""

from __future__ import annotations

import argparse
import csv
import json
import os
import re
from pathlib import Path

import numpy as np

import dpdp_mandel_analytical as an

SCRIPT_DIR = Path(__file__).resolve().parent
VALIDATION_DIR = SCRIPT_DIR.parent
DEFAULT_TEMPLATE = VALIDATION_DIR / "DPDP_N2_dispdriven_fim_eff_direct_mesh10_sameSourcePressure.xml"
DEFAULT_OUT_DIR = VALIDATION_DIR / "mandel_input_tables" / "same_source_pressure_calibrated"


def parse_load_times(template: Path) -> np.ndarray:
  text = template.read_text()
  start = text.index('<TableFunction name="loadFunction0000000"')
  coord_start = text.index('coordinates="{', start) + len('coordinates="{')
  coord_end = text.index('}"', coord_start)
  return np.fromstring(text[coord_start:coord_end].replace(",", " "), sep=" ")


def pressure_calibrated_initials(pc: float, pm_over_pc: float, pf_over_pc: float) -> tuple[np.ndarray, float]:
  """Closest exactly consistent p0 to the requested pressure ratios."""
  requested = pc * np.asarray([pm_over_pc, pf_over_pc], dtype=float)
  storage_load = an.Sbar @ requested
  f0 = -float(an.abar @ storage_load) / float(an.abar @ an.abar)
  p0 = np.linalg.solve(an.Sbar, -an.abar * f0)
  return p0, f0


def displacement_calibrated_initials(pc: float, uz_dimless: float) -> tuple[np.ndarray, float]:
  uz0 = uz_dimless * pc * an.b / (2.0 * an.G)
  f0 = -uz0 / an.b * (1.0 - 2.0 * an.nu) / (1.0 - an.nu)
  p0 = np.linalg.solve(an.Sbar, -an.abar * f0)
  return p0, f0


def uz_from_f(f0: float) -> float:
  return abs(f0) * an.b * (1.0 - an.nu) / (1.0 - 2.0 * an.nu)


def analytical_uz_shape(times: np.ndarray) -> np.ndarray:
  """Return uz(t) / uz(0+) as a positive compression magnitude ratio."""
  tau0 = 1.0e-7
  uz_ref = float(an.invert(3, np.asarray([tau0 * an.t0]))[0])
  ratios = np.ones_like(times, dtype=float)
  mask = times > tau0 * an.t0
  if np.any(mask):
    ratios[mask] = an.invert(3, times[mask]) / uz_ref
  return np.abs(ratios)


def write_vector(path: Path, values: np.ndarray) -> None:
  np.savetxt(path, np.asarray(values, dtype=float), fmt="%.10e")


def write_xml_snippet(path: Path, times: np.ndarray, uz_values: np.ndarray) -> None:
  coords = ", ".join(f"{value:.6e}" for value in times)
  values = ", ".join(f"{value:.6e}" for value in uz_values)
  path.write_text(
      '    <TableFunction name="loadFunction0000000" inputVarNames="{ time }"\n'
      f'      coordinates="{{ {coords} }}"\n'
      f'      values="{{ {values} }}"/>\n'
  )


def write_summary_csv(path: Path, rows: list[dict[str, float | str]]) -> None:
  with path.open("w", newline="") as stream:
    writer = csv.DictWriter(stream, fieldnames=list(rows[0].keys()))
    writer.writeheader()
    writer.writerows(rows)


def maybe_write_xml(template: Path, output_xml: Path, table_dir: Path, p0: np.ndarray, uz_values: np.ndarray) -> None:
  text = template.read_text()
  table_ref = Path(os.path.relpath(table_dir.resolve(), output_xml.parent.resolve())).as_posix()
  text = re.sub(
      r'(name="initialUxFunc"[\s\S]*?coordinateFiles=)"\{[^"]+\}"',
      (
          r'\1"{ '
          f'{table_ref}/xlin.geos, {table_ref}/ylin.geos, {table_ref}/zlin.geos'
          ' }"'
      ),
      text,
      count=1,
  )
  text = re.sub(
      r'(name="initialUzFunc"[\s\S]*?coordinateFiles=)"\{[^"]+\}"',
      (
          r'\1"{ '
          f'{table_ref}/xlin2.geos, {table_ref}/ylin2.geos, {table_ref}/zlin2.geos'
          ' }"'
      ),
      text,
      count=1,
  )
  text = re.sub(r'voxelFile="[^"]*ux\.geos"', f'voxelFile="{table_ref}/ux.geos"', text)
  text = re.sub(r'voxelFile="[^"]*uz\.geos"', f'voxelFile="{table_ref}/uz.geos"', text)
  text = re.sub(
      r'(name="initPressureM"[^>]*fieldName="pressure" scale=")[^"]+',
      rf"\g<1>{p0[0]:.12g}",
      text,
      flags=re.S,
  )
  text = re.sub(
      r'(name="initPressureF"[^>]*fieldName="pressure" scale=")[^"]+',
      rf"\g<1>{p0[1]:.12g}",
      text,
      flags=re.S,
  )
  start = text.index('<TableFunction name="loadFunction0000000"')
  values_start = text.index('values="{', start) + len('values="{')
  values_end = text.index('}"', values_start)
  values = ", ".join(f"{value:.6e}" for value in uz_values)
  text = text[:values_start] + values + text[values_end:]
  generated_comment = (
      "<!-- Generated by script/generate_same_source_p0_uz.py: same-source p0/uz, "
      'crossStorageOffDiagScale unchanged. -->'
  )
  if text.startswith("<?xml"):
    declaration_end = text.index("?>") + len("?>")
    text = text[:declaration_end] + "\n" + generated_comment + text[declaration_end:]
  else:
    text = generated_comment + "\n" + text
  output_xml.write_text(text)


def parse_args() -> argparse.Namespace:
  parser = argparse.ArgumentParser(description=__doc__)
  parser.add_argument("--mode", choices=("pressure", "displacement"), default="pressure")
  parser.add_argument("--pc", type=float, default=1.0e6, help="Load scale Pc in Pa.")
  parser.add_argument("--pm-over-pc", type=float, default=0.455)
  parser.add_argument("--pf-over-pc", type=float, default=0.488)
  parser.add_argument(
      "--uz-dimless",
      type=float,
      default=0.37219062321993224,
      help="Initial 2G*uz/(Pc*b), used only with --mode displacement.",
  )
  parser.add_argument("--template", type=Path, default=DEFAULT_TEMPLATE)
  parser.add_argument("--out-dir", type=Path, default=DEFAULT_OUT_DIR)
  parser.add_argument("--xml-out", type=Path, help="Optional generated GEOS XML path.")
  return parser.parse_args()


def main() -> int:
  args = parse_args()
  out_dir = args.out_dir.resolve()
  out_dir.mkdir(parents=True, exist_ok=True)

  if args.mode == "pressure":
    p0, f0 = pressure_calibrated_initials(args.pc, args.pm_over_pc, args.pf_over_pc)
    source = {
        "mode": "pressure",
        "requested_pm_over_pc": args.pm_over_pc,
        "requested_pf_over_pc": args.pf_over_pc,
    }
  else:
    p0, f0 = displacement_calibrated_initials(args.pc, args.uz_dimless)
    source = {
        "mode": "displacement",
        "requested_uz_dimless_2Guz_over_Pcb": args.uz_dimless,
    }

  uz0 = uz_from_f(f0)
  uz_dimless = 2.0 * an.G * uz0 / (args.pc * an.b)
  residual = an.Sbar @ p0 + an.abar * f0
  relative_residual = float(np.linalg.norm(residual) / max(np.linalg.norm(an.Sbar @ p0), 1.0e-300))

  times = parse_load_times(args.template)
  uz_values = uz0 * analytical_uz_shape(times)

  # Preserve the existing lateral/top initial displacement ratio while removing the mixed absolute scale.
  old_uz = float(np.loadtxt(VALIDATION_DIR / "mandel_input_tables" / "uz.geos", ndmin=1)[-1])
  old_ux = float(np.loadtxt(VALIDATION_DIR / "mandel_input_tables" / "ux.geos", ndmin=1)[-1])
  ux0 = old_ux * uz0 / old_uz

  for name in ("xlin.geos", "ylin.geos", "zlin.geos", "xlin2.geos", "ylin2.geos", "zlin2.geos"):
    (out_dir / name).write_text((VALIDATION_DIR / "mandel_input_tables" / name).read_text())
  write_vector(out_dir / "ux.geos", np.asarray([0.0, ux0]))
  write_vector(out_dir / "uz.geos", np.asarray([0.0, uz0]))
  write_vector(out_dir / "load_time.geos", times)
  write_vector(out_dir / "load_uz.geos", uz_values)
  write_xml_snippet(out_dir / "loadFunction0000000_snippet.txt", times, uz_values)

  summary = {
      **source,
      "pc_Pa": args.pc,
      "pm0_Pa": float(p0[0]),
      "pf0_Pa": float(p0[1]),
      "pm0_over_pc": float(p0[0] / args.pc),
      "pf0_over_pc": float(p0[1] / args.pc),
      "f0": float(f0),
      "uz0_m": float(uz0),
      "ux0_m": float(ux0),
      "uz_dimless_2Guz_over_Pcb": float(uz_dimless),
      "initial_closure_relative_residual": relative_residual,
      "t0_s": float(an.t0),
      "G_Pa": float(an.G),
      "nu": float(an.nu),
      "Sbar_00": float(an.Sbar[0, 0]),
      "Sbar_01": float(an.Sbar[0, 1]),
      "Sbar_10": float(an.Sbar[1, 0]),
      "Sbar_11": float(an.Sbar[1, 1]),
      "abar_0": float(an.abar[0]),
      "abar_1": float(an.abar[1]),
  }
  (out_dir / "same_source_p0_uz_summary.json").write_text(json.dumps(summary, indent=2, sort_keys=True) + "\n")
  write_summary_csv(out_dir / "same_source_p0_uz_summary.csv", [summary])

  if args.xml_out:
    args.xml_out.parent.mkdir(parents=True, exist_ok=True)
    maybe_write_xml(args.template, args.xml_out.resolve(), out_dir, p0, uz_values)

  print(f"mode = {args.mode}")
  print(f"out_dir = {out_dir}")
  print(f"pm0 = {p0[0]:.12g} Pa  ({p0[0] / args.pc:.12g} Pc)")
  print(f"pf0 = {p0[1]:.12g} Pa  ({p0[1] / args.pc:.12g} Pc)")
  print(f"uz0 = {uz0:.12g} m")
  print(f"2G*uz0/(Pc*b) = {uz_dimless:.12g}")
  print(f"initial closure relative residual = {relative_residual:.3e}")
  if args.xml_out:
    print(f"xml = {args.xml_out.resolve()}")
  return 0


if __name__ == "__main__":
  raise SystemExit(main())
